version: '3.1'
services:
  dbpostgres:
    container_name: dbpostgreschatapp
    image: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chatter
  chatapp:
    container_name: chat_app
    build: ./
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbpostgres/chatter
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - dbpostgres